FROM alpine:latest

LABEL version="1.0.0" maintainer="alpine" os="ubuntu"

ENV CONTAINER_USER="astou"
RUN adduser $CONTAINER_USER --disabled-password 

CMD echo "hello-alpine, I’m $CONTAINER_USER and this is a container from my first image" 

